version: '3.8'

services:
  # Base de datos MySQL compartida
  mysql-db:
    image: mysql:8.0
    container_name: mysql-database
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API de Categorías
  categories-api:
    build:
      context: ./categorias
      dockerfile: Dockerfile
    container_name: categories-service
    ports:
      - "8089:8080"  # 8089 externo -> 8080 interno (Spring Boot default)
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/test?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - app-network
    restart: on-failure

  # API de Productos
  products-api:
    build:
      context: ./products/products/pdts
      dockerfile: Dockerfile
    container_name: products-service
    ports:
      - "8088:8080"  # 8088 externo -> 8080 interno (Spring Boot default)
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/test?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      CATEGORIES_SERVICE_URL: http://categories-api:8080
      CATEGORIES_API_URL: http://categories-api:8080/api/categorias
    networks:
      - app-network
    restart: on-failure

  # Frontend Angular
  frontend:
    image: ryuzakizeitan/frontend-products-cats:latest
    # Para desarrollo local, descomenta las siguientes líneas y comenta la línea 'image':
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "80:80"  # Exponer en el puerto 80 para producción
    depends_on:
      - categories-api
      - products-api
    networks:
      - app-network
    # NOTA: Si tu Angular está construido con URLs absolutas a localhost:8088 o localhost:8089, debes cambiarlas a:
    # http://products-api:8080 y http://categories-api:8080 para funcionar en Docker.
    # En producción, usa un proxy en Nginx para redirigir /api/* a los microservicios.

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
