version: '3.8'

services:
  # Base de datos MySQL compartida
  mysql-db:
    image: mysql:8.0
    container_name: mysql-database
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API de Productos
  products-api:
    build:
      context: ./products/products/pdts
      dockerfile: Dockerfile
    container_name: products-service
    ports:
      - "8088:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/test?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      CATEGORIES_SERVICE_URL: http://34.134.60.70/categories
      CATEGORIES_API_URL: http://categories-api:8080/api/categorias
    networks:
      - app-network
    restart: on-failure

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
